name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  root-tests:
    name: Tests (root)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 24
        uses: actions/setup-node@main
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint

  projects-tests:
    name: Projects
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 24
        uses: actions/setup-node@main
        with:
          node-version: 24

      - name: Install Dependencies
        run: cd projects && npm install

      - name: Build
        run: cd projects && npm run build

      - name: Test
        run: cd projects && npm test
